apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pvc-mongodb-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /oagid_nfs/mongodb-pvc-mongodb-1
