apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-mongodb-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /oagid_nfs/mongodb-pv-mongodb-2
