singleuser:
  cloudMetadata:
    blockWithIptables: false
  networkPolicy:
    enabled: false
  storage:
    dynamic:
      storageClass: nfs-client
  profileList:
    - display_name: "GPU Server"
      description: "Spawns a notebook server with access to a GPU"
      kubespawner_override:
        extra_resource_limits:
          nvidia.com/gpu: "1"
hub:
  config:
    JupyterHub:
      authenticator_class: ldapauthenticator.LDAPAuthenticator
    LDAPAuthenticator:
      allowed_groups:
        - cn=jupyterhub,cn=groups,dc=oagid,dc=local
      bind_dn_template:
        - uid={username},cn=users,cn=accounts,dc=oagid,dc=local
      server_address: 172.16.6.52
      escape_userdn: false
