singleuser:
  cloudMetadata:
    blockWithIptables: false
  networkPolicy:
    enabled: false
  storage:
    dynamic:
      storageClass: nfs-client
  profileList:
    - display_name: "GPU Server"
      description: "Spawns a notebook server with access to a GPU"
      kubespawner_override:
        extra_resource_limits:
          nvidia.com/gpu: "1"
