apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-f7bb5c5f-7605-4dc6-8c50-dbe6ed81e6da
spec:
  capacity:
    storage: 10Gi  # match or exceed the PVC request
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client  # must match the PVC
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: oagid_nfs
    path: /oagid_nfs/jupyterhub-hub-db-dir-pvc-f7bb5c5f-7605-4dc6-8c50-dbe6ed81e6da
  claimRef:
    namespace: jupyterhub
    name: hub-db-dir
